a = input('masukkan bilangan 1 : ')
b = input('masukkan bilangan 2 : ')
c = int(b) - int(a)
d = int(b) + int(a)
e = int(b) * int(a)
f = int(b) / int(a)
print('hasil dari pengurangan: ' + str(c))
print('hasil dari pejumlahan: ' + str(d))
print('hasil dari perkalian: ' + str(e))
print('hasil dari pengurangan: ' + str(f))
